### ISSUE TITLE
Can't update to v1.05

### ISSUE THREAD

**Issue by ghost** [BlupGithub/Blup-IDE#1]
Hi, 

Just after I got the email about the new version knowing that I have v1.04, I tried updating from the file options in the app but it says there's no update, tried also to download a new EXE setup file but the file itself show the same version 1.04.

Note: the 1.04 has lots of bugs I just can't even head start with it.

Thanks

**Comment by SahajRana** [comment]
The Windows version will be available by tomorrow morning. There were some
delays due to one problem.


Regards,
Until next time,
[image: sahaj-rana/] <https://www.linkedin.com/in/sahaj-rana/>
Sahaj Rana
Founder & CEO
[image: blup-logo/] <https://blup.in/>
[image: blup-linkedin/] <https://www.linkedin.com/company/bluptool/>
[image: blup-youtube/] ***@***.***_tool>
[image: blup-twitter/] <https://twitter.com/Blup_tool>
[image: blup-instagram/] <https://www.instagram.com/blup_tool/>

**Comment by SahajRana** [comment]
Update is live!
